Revert "build: set custom fingerprint in ro.build.fingerprint too"
This reverts commit 5b898b599c6d6e82fb40009d1cfe31ad5081a885.

Causes a conflict when using static sysprops in device tree.

error: found duplicate sysprop assignments